### ISSUE TITLE
submit: AtCoder上のgolf用に利便性向上

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#177]
#108 #114 #139 https://twitter.com/kotatsugame_t/status/1033820622093086720

**Comment by kmyk** [comment]
submit時の `--open` をdefaultにしました
@fukatani さんの https://github.com/fukatani/rust-gui-debugger とかがもしかしたら壊れるかもだが「できるだけすべて安全側に倒す」という方針とも合致するので仕方ないという判断です。もし壊れたら `--no-open` とかしてくださいすまない

**Comment by kmyk** [comment]
これping飛んだのかな
右側の表示は1 participantのままだけど

**Comment by kmyk** [comment]
設定ファイル作らなくてもよさそうな感じになったね

**Comment by fukatani** [comment]
ping来ました。わざわざありがとうございます！
私が勝手に使ってるだけなので、互換性はお気になさらず、開発を進めていただいて大丈夫です。
いざとなったら、こちらはバージョンを指定します。
