### ISSUE TITLE
discuss to finish supporting Python 3.5

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#465]
https://github.com/kmyk/online-judge-tools/pull/218 から Python 3.5 をサポートしていますが、そろそろサポートを切ることを検討しておきたいです。
個人的には、3.5 のユーザがたくさん (3割以上ぐらい？) いるなら控えたいが、十分に少ない (1割以下ぐらい？) なら切ってしまいたいと感じています。

## 主な理由

-   3.6 にならあるけど 3.5 では使えない機能であって、使いたいものがある。具体的には namedtuple https://docs.python.org/ja/3.6/library/typing.html#typing.NamedTuple
-   そろそろ AtCoder の Python が 3.5 から 3.7 になる
-   他にもまとめて破壊的に整理したいのでついでにやるとちょうどよさそう
-   とても古い環境でも動き続けてほしいような種類のプログラムではない
-   Python 3.5 の環境だと `setuptools` も古くてどうせ一発では導入できない https://github.com/kmyk/online-judge-tools/blob/60a5b937d9978cc96a83d08c7fc6fbeec6d526a4/setup.py#L10

エンドユーザに直接の利益はなく、主に開発側が楽になります。
ユーザの利益は重要ですが、これはそもそもは我々自身 (ただし実装をする人間のみでなく、バグ報告や機能要望を上げてくれたり宣伝をしてくれたりするユーザを含む) が使うためのもののはずなので、商用のアプリケーション (たとえばウェブサイト https://amazon.co.jp/) とは違ってお客様の方向のみを向き続ける必要性はありません。

## 反対理由

次の 1 点のみ (しかし容易には無視できない) です。

-   Python 3.5 のみしかない環境で利用できなくなる

## Python の release cycle

-   Python 3.5 は 2015年9月に公開で、いまはセキュリティの問題なら直す (バグは直さない) 期間、2020年9月に完全にサポート切れ
-   Python 3.7 が現在の最新で 2018年6月に公開
-   Python 3.8 ががもうすぐ 2019年10月に公開予定

https://devguide.python.org/#status-of-python-branches

## 主要な OS とそのデフォルトのバージョン

-   Ubuntu 18.04 LTS (2018年4月) は 3.6 https://packages.ubuntu.com/bionic/python/python3
-   Ubuntu 16.10 (2016年10月、もうサポート切れ) は 3.6
-   Ubuntu 16.04 LTS (2016年4月) は 3.5 https://packages.ubuntu.com/xenial/python3
-   Windows は exe に固めて配布することになるので無視してよい。そうでなくても https://www.python.org/downloads/ のページからぽちぽちやってインストールするので常に最新と思ってよい
-   Mac OS は使ってないので何も知らない (教えてください)

**Comment by fukatani** [comment]
私は3.5ユーザーですけど、上げなきゃなという危機感はあるのでこれを期にバージョン上げたいです。
ところで、3.7のサポートを開始するのはどうでしょう？appveyorの結果を見ると今のままで動きそうですし。

ちなみにAtCoderは3.4だったはずです。

**Comment by kmyk** [comment]
これに依存するツールへの影響範囲の考察が必要なのを忘れてた。他プロジェクトのCIをいきなり落とすような結果になるとまずいので調査や相談は必要そう。

**Comment by kmyk** [comment]
3.7 のサポートはあるとよさそう。
しかし何もしなくても動いているはずなので、特に何もしなくてよさそう。

**Comment by kmyk** [comment]
https://github.com/kmyk/online-judge-tools/pull/469 を見た感じでは他のツールへの影響はあまり心配しなくてよさそう

**Comment by kmyk** [comment]
closed. it's now EOL and we can remove 3.5. see #809 instead
