### ISSUE TITLE
make an extension for VSCode

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#529]
Many people want to integrate online-judge-tools with Visual Studio Code.

I heard that some people have integrated as their local settings, but we should make them a distributable package (or, at least, a document).

**Comment by BarnikRay** [comment]
I would like to work on this issue

**Comment by kmyk** [comment]
@BarnikRay This task is a little bit tough, and requires your understanding about competitive programming and the use case of this tool. Are you Okay?

**Comment by BarnikRay** [comment]
Yeah I'm conversant with competitive programming and I'm aware of this tool. I'll be able to accomplish this task

**Comment by kmyk** [comment]
@BarnikRay I got it. I assigned you to this issue. Thank you!

**Comment by BarnikRay** [comment]
Thanks! :)

**Comment by kmyk** [comment]
By the way, I'll leave it to you about how you implement it.
I started to use VSCode few days ago. So I don't much know what VSCode extension can do, and cannot make the detailed specification. sorry 🙇 

At least, I want:

-   a command to download sample cases (which asks a URL of a problem)
-   a command to test with sample cases in VSCode

**Comment by BarnikRay** [comment]
Okay.. Thanks for the specifications. I'll work on them and let you know about my implementation plans

**Comment by kmyk** [comment]
@BarnikRay are you still working on this issue?

**Comment by BarnikRay** [comment]
Hi.. I was trying to figure out a way to make the extension but vscode extensions are all written in typescript and I couldn't find a way to integrate the same..

**Comment by fukatani** [comment]
Hi! I found `black` (Python formatter) extention for VSCode.

I think code here may help us.
https://github.com/joslarson/black-vscode/blob/master/src/BlackEditProvider.ts#L126

They use `child_process` in node.js.

**Comment by kmyk** [comment]
closed due to age and no progress.

If you want to find a such extension, you should also see https://github.com/jmerle/competitive-companion
