### ISSUE TITLE
translate Japanese documents to English

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#530]
I have written two pages in Japanese.
- [x] https://online-judge-tools.readthedocs.io/en/master/introduction.ja.html
- [x] https://online-judge-tools.readthedocs.io/en/master/run-ci-on-your-library.html

These documents should be translated to English.

**Comment by DilkiSasikala** [comment]
I would like to attempt this...

**Comment by kmyk** [comment]
@DilkiSasikala Okay. Thank you.

**Comment by pieceofeden** [comment]
Is this issue still open ? I'd like to contribute

**Comment by kmyk** [comment]
@pieceofeden Yes, it's still open.
It seems that @DilkiSasikala stopped attempting. (if not, please claim > @DilkiSasikala)

**Comment by fukatani** [comment]
We can divide work into appropriate units.

I mean that we don't have to translate all of these documents by 1 PR.
I think the most valuable document to be translated is https://online-judge-tools.readthedocs.io/en/master/introduction.ja.html .

Moreover, for example, translation of the fiirst three chapters of introduction is also welcome.

**Comment by pieceofeden** [comment]
Should I create a separate intoduction.en.rst for the english version ? Please have a look once before i send a PR.
(https://github.com/pieceofeden/online-judge-tools/blob/translate-Japanese-documents-to-English-%23530/docs/introduction.ja.rst)

**Comment by fukatani** [comment]
@pieceofeden 
Thank you for translation!

> Should I create a separate intoduction.en.rst for the english version ?

Yes, you're right.

It seems, some documents are broken. (Mainly, spacing) 
ex.
- `. / a.out` -> `./a.out`
- `oj g / i. / generate.py` -> `oj g/i ./generate.py`

Also, some markdown is broken.
ex.
- judge.py '' -> judge.py
- for i in test / *. In; do ./a.out <$ f> $ {f / .in / .out} ; -> `for i in test / *. In; do ./a.out <$ f> $ {f / .in / .out} ;`

Could you fix them?

**Comment by fukatani** [comment]
Almost closed by #591. However, part of CONTRIBUTING.md is remained.

**Comment by kmyk** [comment]
The translation is already finished.
