### ISSUE TITLE
Add unittest for dispatch.

### ISSUE THREAD

**Issue by fukatani** [online-judge-tools/oj#556]
In #549, we added unittests for `dispatch` AtCoder and Codeforces.
To increasing test coverage, we should add unittests for other contest (HackerRank, CS Academy, ...).

Not only tests for all other contests, tests for the part of contests are welcome.

**Comment by zakiindra** [comment]
Can I work on this issue?

**Comment by fukatani** [comment]
Yes, of course!

**Comment by kmyk** [comment]
There are no unittests for this but it's covered by many integration tests.
