### ISSUE TITLE
Add unittest for DownloadHistory

### ISSUE THREAD

**Issue by fukatani** [online-judge-tools/oj#565]
As you can see [here](https://coveralls.io/builds/26422282/source?filename=onlinejudge/_implementation/download_history.py), half of `download_history.py` is not covered by unittests.
At least, I want to test `DownloadHistory.get` fucntion.

We can test this module by 3 steps.
- Clear `utils.cache_dir / 'download-history.jsonl'`.
- Execute `oj d`, or directly instanciate `DownloadHistory` and call `DownloadHistory.add`.
- Instanciate `DownloadHistory` and call `DownloadHistory.get` and veryfy its return value.

**Comment by meda123** [comment]
Hi - May I work this issue?

**Comment by fukatani** [comment]
Yes, of course!

**Comment by meda123** [comment]
> Yes, of course!

Awesome. I'll read through the documentation and come back with any clarifying questions.

**Comment by luchiago** [comment]
Hi @meda123 you still working on that? I want to give a try.

**Comment by kawacchu** [comment]
@meda123 
Are you still interested in this issue?
If not or no response, I will assign another contributor to this issue.

**Comment by kawacchu** [comment]
@luchiago 
Thank you for participating!
I assigned you to this issue.
If this task is difficult, please feel free to ask us.

**Comment by kmyk** [comment]
Some integration tests already exist.
