### ISSUE TITLE
apply `parse_content` function to another contest

### ISSUE THREAD

**Issue by kawacchu** [online-judge-tools/oj#573]
#553 was solved by #561 (yukicoder only).

Through this issue, we apply `parse_content` (in onlinejudge/_implementation/utils.py) to other services.

<br/>

**PROGRESS**

- [x] AtCoder
- [x] yukicoder
- [x] Anarchy Golf
- [x] Codeforces
- [x] HackerRank
- [x] Aizu Online Judge (including Arena)
- [x] CS Academy
- [ ] PKU JudgeOnline
- [ ] Kattis
- [x] Toph (Problem Archive)
- [x] Facebook Hacker Cup
- [x] Library Checker (https://judge.yosupo.jp)

**Comment by kawacchu** [comment]
`parse_content` is used in scraping only.
So services we don't do scraping will be solved automatically in this issue.

**Comment by kmyk** [comment]
We uses some API for AOJ, HackerRank , CSA and Library Checker, not scraping.

**Comment by kawacchu** [comment]
@kmyk Thanks! I`ll work on from AtCoder.

**Comment by kawacchu** [comment]
In Anarchy Golf, we can parse sample cases correctly without `parse_content`.

**Comment by kawacchu** [comment]
It seems we use API for Facebook Hacker Cup, isn't it?

**Comment by kmyk** [comment]
We don't use `parse_content` on FHC.
However it's unnecessary because the samples are given via HTTP headers, not HTML, so we can add a check mark for this issue.

**Comment by kmyk** [comment]
いや、API って `utils.parse_content` の関数のことでなくて FHC 側が用意している endpoint のことか。それなら利用しています。

**Comment by kmyk** [comment]
これたぶん大丈夫だと思うので閉じておきます
