### ISSUE TITLE
imp is deprecated.

### ISSUE THREAD

**Issue by fukatani** [online-judge-tools/oj#677]
Currently, `setup.py` uses `imp` module.

I tried `pip uninstall colorama`
```python
version = importlib.import_module('onlinejudge.__about__')
```
But it does not work.
I have to install `colorama` and other dependency in advance, but user may not install them before installing `oj`.

**Comment by kawacchu** [comment]
> But it does not work.

`importlib` works well in my local environment (Python 3.7.3).

```information.py
import importlib

information = importlib.import_module('onlinejudge.__about__')

package_name = information.__package_name__
version = information.__version__

print(package_name) # online-judge-tools
print(version) # 7.8.0

```

**Comment by fukatani** [comment]
Thx! 
Could you uninstall `colorama` and try `pip install -e .`again?

We want to import `onlinejudge.__about__` but not `onlinejudge`.

**Comment by kawacchu** [comment]
You're right, I have found `ModuleNotFoundError` about `colorama`.

**Comment by kmyk** [comment]
closed due to age and low priority
