### ISSUE TITLE
作り直し

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#687]
## 問題

現在、以下のようないくつかの問題があります:

- a. 入出力の自動生成をうまくやってくれるツールがない
- b. コンテスト用のディレクトリ一括生成の機能が望まれている
- c. 問題ごとの時間制限やメモリ制限や許容誤差を認識してよしなにしてほしい
- d. 提出前に自動で formatter を噛ませたい
- e. 乱択ケース自動生成用の (ランダムに木をひとつ選んで作ったりするような) ライブラリがほしい

(a.) は私が困っています。現状でも [atcoder-tools](https://github.com/kyuridenamida/atcoder-tools) とか最近は [nejiko96/at_coder_friends](https://github.com/nejiko96/at_coder_friends) (なぜか動かないので試せてないけど) はあります。しかし (x.) AtCoder にしか対応していない、(y.) 入出力テンプレの自動生成しかしてくれない、(z.) 入出力でなく入力部分にしか対応していない、などを理由として不満です。せっかく自動生成するのなら、解法自動生成は難しめなのでひとまず見送るとしても、ランダムケース生成器や作問用 validator は生成してほしくないですか？ 私は生成してほしいです。

(b.) は私はあまり困っていませんが (あるとうれしいのは分かる)、予想以上に望まれている様子が観察できます。
要望が多いのはおそらくこれが「誰でも思い付けてかつ簡単に実装できるような改善点」、いわゆる自転車置き場の色になっているからだと思っています。なので要望自体は無視してもいいんですが、(a.) を解決するにはたくさんファイルを作る必要があり、ついでに解決されます。
固定でディレクトリを作ったり設定ファイルを読みにいくような最適化をすると、便利ではあるが用途も固定され、たとえば [online-judge-verify-helper](https://github.com/kmyk/online-judge-verify-helper) や [rujaion](https://github.com/fukatani/rujaion) のような派生ツールがかなり出てきにくくなるのでよくない、という立場については変えていません。

(c.) は困っていませんが、あると安心です。
ローカル環境では間に合うけどリモート環境では CPU の速度差のため間に合わない系のうっかり TLE がこわいので、そのあたりを認識して警告してほしい。
あと MLE うっかりもこわい。
[atcoder-tools](https://github.com/kyuridenamida/atcoder-tools) は部分的にやってくれていますが、AtCoder 限定なので不満です。

(d.) は私がすこし困っています (alias を張れば十分なのでそんなには困ってない)。
[online-judge-verify-helpr](https://github.com/kmyk/online-judge-verify-helper) を利用していると、提出前に自動で依存ファイルをまとめたりしてほしい気持ちになります。

(e.) は私が困っています。
さすがに誰かは作っていそうだけど公開はされてなさそう。
これだけ他との関連が薄いですが、ランダムケースの自動生成のついでに解決できるので解決したい。

## 解決策

上記の問題をすべて解決するツールを誰かが書けば、すべて解決します。
[atcoder-tools](https://github.com/kyuridenamida/atcoder-tools) を拡張するのはありなんですが、すでに完成しているものを組み換えることになるのでしんどいです。@kyuridenamida 本人がやるなら別として、どうせ大規模に入れ替えることになるので [atcoder-tools](https://github.com/kyuridenamida/atcoder-tools) を参考にして再設計し再実装した方が楽でしょう。

ずっと昔からある問題ですが、誰も解決してくれる気配がないので私がやるしかなさそう。
開発を進めたいものが他にいくつかあるのでしばらく先になりますが、もし私がやるとすると、次を順に行います:

1. 外部のリポジトリで `oj2` とか `oj-prepare-contest` のような wrapper コマンドを作る
2. このリポジトリを `online-judge-api-client` などの名前に変え、`oj2` のレポジトリを `online-judge-tools` に改名する

(2.) はユーザのスムーズな移行と役割の明確化のためです。つまり、ユーザに「新しいツールをインストールしろ」という面倒を要求することなしに新しいツールを導入させることと、現状の online-judge-tools のライブラリとしての用法を強調することが目的です。
現状の `oj` コマンドは残しておいてメンテは続けます。

ところで、(1.) はそのうち私が勝手にやるだけなんですが (2.) については別で、メンテを手伝ってもらっているふたり @fukatani @kawacchu はこれに反対する権利を持ちます。もちろん、反対があってもその根拠に説得力がなければ無視します。

---

cc: @kyuridenamida @tatamo

**Comment by kyuridenamida** [comment]
> b. コンテスト用のディレクトリ一括生成の機能が望まれている

> 要望が多いのはおそらくこれが「誰でも思い付けてかつ簡単に実装できるような改善点」、いわゆる自転車置き場の色になっているからだと思っています。

コンテストにおける問題ダウンロードがメインユースケースではある以上、「自転車置き場の色」だとは思いませんが、これは単に"責務"の問題だと思うのでメンテナの意見に従います。

少なくともコンテストに紐付いた問題url集合の取得くらいまではojが提供しても良いのではないのでしょうか。ユーザーが手元でwrapperを書くとしても、atcoderのコンテストhtmlをパースする状況は避けたい。

**Comment by kmyk** [comment]
> コンテストにおける問題ダウンロードがメインユースケースではある以上、

この指摘は正しいです。みんなが口を出したくなる問題だという点は変わりませんが、どうでもよい問題ではないですね。

> 少なくともコンテストに紐付いた問題url集合の取得くらいまではojが提供しても良いのではないのでしょうか。

分かります。分かるのだけど、実際にそうすべきかは悩んでいます。
「`oj` コマンドの本来の役割は通常の問題を解くときに使うコマンドである」「現状の online-judge-tools は Python のライブラリも提供している (`import onlinejudge` などとすると `Contest.list_problems()` みたいなメソッドがある)」という状況で、これらの責務を曖昧にするサブコマンドは追加したくない気持ちがあるためです。

**Comment by kyuridenamida** [comment]
> 上記の問題をすべて解決するツールを誰かが書けば、すべて解決します。

力強い解決策提案すき

> atcoder-tools を拡張するのはありなんですが、すでに完成しているものを組み換えることになるのでしんどいです。@kyuridenamida 本人がやるなら別として、どうせ大規模に入れ替えることになるので atcoder-tools を参考にして再設計し再実装した方が楽でしょう。

僕は直近でやる元気はないです。すみません。誰かが再設計してくれることに対して肯定的です。

atcoder-toolsの入力・問題のメタデータ解析に関してですが、現状内部的には問題からそれらの抽出を行った後は別にatcoderであることや"入力であること"にも依存はしてないです(下記URL参照)。ただ、出来合いのものを把握するより一度様々なジャッジに対応する前提で作りなおしたほうが迅速にbetterなものができると思ってるのでともかく再実装することに対しては肯定的です。うちのリポジトリからatcoderに依存しない部分をはがしてもらうというのもひとつアリだとは思いますがこれはこれで面倒かな?

- 問題文のメタデータ (https://github.com/kyuridenamida/atcoder-tools/blob/master/atcodertools/constprediction/models/problem_constant_set.py)
- 入力の中間形式 (https://github.com/kyuridenamida/atcoder-tools/blob/master/atcodertools/fmtprediction/models/format.py)

---- 

cc. @chaemon

cc飛ばしておきます。 ちょうど最近yukicoder対応しませんか?みたいな話持ちかけられましたし、atcoder-tools側の問題メタデータ抽出の充実に多大なる貢献してくださっているので、きっとこの話に対して関心があると思います。

**Comment by kyuridenamida** [comment]
> 分かります。分かるのだけど、実際にそうすべきかは悩んでいます。
「oj コマンドの本来の役割は通常の問題を解くときに使うコマンドである」「現状の online-judge-tools は Python のライブラリも提供している (import onlinejudge などとすると Contest.list_problems() みたいなメソッドがある)」という状況で、これらの責務を曖昧にするサブコマンドは追加したくない気持ちがあるためです。

実はそこの責務を分離することによるUX的な恩恵がいまいち思いついていません。恩恵があるとしたら、開発側のメンテコストかなとは思っています。背景にある思想などあれば知りたいです。

勝手な意見ですが、`oj`コマンドはonline-judge-toolsで提供されているPythonのライブラリのcommand line frontendという立場もユーザー的にはまた自然だとは思います。ただライブラリとoj2コマンドを分離するという方向性なら、現状の`oj`の責務はそのままで`oj2`でそのへんの責務拡大を狙ってもいいのなと思います。

**Comment by fukatani** [comment]
ojのwrapperを作るという方針はいいと思います。
→私もリポジトリを分けたほうがいいのかよくわかってないんですが、ojはテストやレビュー過程が厳しくなってるので、wrapperはまずは自由に書きたいとか？

また本当にユーザーが欲しいものを考えてみることも面白いのかなと。
ユーザーは本当はディレクトリ構造を欲しているんでなくて、「コンテスト中に問題を手間なくスイッチしたい」というのが彼らの求めるものです。

であれば、「このコンテストにはA-F問題がある、そしてあなたは今AをACしています、どれを解きますか？」と聞かれてBを選んだら、Bがダウンロードされてsubmit先もオプションつけずともBに指定されるみたいな体験を提供することもできます。

私自身は、ブラウザ（Selenium）でコンテストページを開いた→開いたということは解いている→解いているということはダウンロードしちゃえばよい。みたいな体験が理想的だと思っています。
(Rujaionもそのために生まれてます。右クリックメニューだけで問題が遷移し、ダウンロードされます。)
だってブラウザでコンテストページを指定したのに、ojに対して問題を指定しなきゃいけないなんて二度手間じゃないですか？

**Comment by fukatani** [comment]
リリースタイミングを合わせるのが楽という意味ではwrapperとojを一緒のリポジトリにするメリットはあります。
あとojはなんだかんだでスターを取ってるし、ドキュメント(awesome-competitive-programmingなど)からリンクを貼られたりしているので、継続性を残したいという思いもあります。(ソフトウェアエンジニアリングの本質ではないかもしれませんが。)

tensorflowに飲み込まれたkerasのように、後から合流するのもあり。

**Comment by kmyk** [comment]
たぶん明確にしておいた方がよいこと:

online-judge-tools は様々なオンラインジャッジに対する API ライブラリ (`oj` コマンドは標準で付属する) であり、その wrapper は command line frontend です (ユーザが直接使うのは `oj` なのでいまはそうは見えてないでしょうが、新しい wrapper が完成すればこの認識に落ち着くはず)。
現状はこれらのふたつ (API としての役割と frontend としての役割) が混ざっている (混ざっててもユーザはあまり困らない) のですが、この機会に分離したい気持ちがあります。

---

@kyuridenamida 

> うちのリポジトリからatcoderに依存しない部分をはがしてもらうというのもひとつアリだとは思いますがこれはこれで面倒かな?

量は分かりませんが、これはやると思います (ありがとうございます)。
少なくとも入出力生成のテンプレートとかはかなりそのまま借りそう。

> 実はそこの責務を分離することによるUX的な恩恵がいまいち思いついていません。恩恵があるとしたら、開発側のメンテコストかなとは思っています。背景にある思想などあれば知りたいです。

これは良い質問だと感じます。なぜなら「UX的な恩恵は何か？」と問われるとうまく説明できなくて困るので。
気持ちとしてはやはり「API 部分と frontend 部分はきっちり区別したい」です。後方互換性をきっちり守るべきところと多少 UI が変わってもよいところを混ぜると、誰かがその境界を勘違いしただけで色々なものが壊れてしまいます (UX的な説明)。
「`oj` コマンドを積極的に API として使う人間はユーザでなくて開発者の側のはずで、開発者なら Python ライブラリの部分を使ってほしい」みたいな気分もあります。

新しく `oj-api` のようなコマンドを作るのはよいと思うのですが、それは Python ライブラリ部分の劣化したものを作って二重に管理するだけになるのでしんどいです。

---

@fukatani 

> リポジトリを分けたほうがいいのか

上で説明したように、API と frontend のふたつは本来別のもののはずです。なので分けたいです。

> だってブラウザでコンテストページを指定したのに、ojに対して問題を指定しなきゃいけないなんて二度手間じゃないですか？

このあたりはそもそも Python で書いて端末上で実行しているのが悪いです。実は TypeScript で書いてブラウザ上で実行できるようにするのが正解 (例: [jmerle/competitive-companion](https://github.com/jmerle/competitive-companion)) だったことが知られています。

> また本当にユーザーが欲しいものを考えてみることも面白いのかなと。

それはそう。そして本当にユーザーが欲しいものを考えると、「手間を減らしたい」はそうですが、そもそも欲しいのは「問題を素早く解きたい」とか「コンテストで勝ちたい」です。
つまり、URL の入力の回数を減らしたりディレクトリの移動を減らしたりの数秒を削ることは重要でなくて、ランダムケース自動生成とか解法自動生成とかを考えるべきです。

**Comment by Tatamo** [comment]
> online-judge-tools は様々なオンラインジャッジに対する API ライブラリ
フロントエンドの話が盛り上がっている中別の話になってしまうかもしれませんが、
(a.)(c.)(e.)は「問題の内容を認識する」など、問題を解く作業そのものの補助で、
(b.)(d.)や問題提出・サンプルダウンロード機能などは問題を解くという作業以外を主眼としているような印象があります。
API部分とフロントエンド部分を分けるのと同様に、API部分の中でも提供される機能を明確に整理する・必要に応じて分割するようなことは考えられないでしょうか？

**Comment by kmyk** [comment]
@Tatamo 

なんとなく言いたいことはわかります。しかしその分割はすでに済んでいるはずです。

online-judge-tools の [Python ライブラリ部分](https://online-judge-tools.readthedocs.io/en/master/onlinejudge.html) (API 部分) からは問題提出・サンプルダウンロード機能などしか提供しておらず、`oj` コマンド (フロントエンド部分) ではテストの実行・ランダムケースの生成補助などを中心として提供しています。これはまさに (a.)(c.)(e.) と (b.)(d.) の分割です。

**Comment by Tatamo** [comment]
なるほど、ありがとうございます。
個人的な印象として(b.)(d.)がフロントエンド側寄りの部分という認識だったので、(a.)(c.)(e.)はライブラリ側かと思っていました。

とはいえ、online-judge-toolsのライブラリの軸があくまでコンテストサイトとの通信にあるのであれば、問題内容そのものを解析していい感じにやってくれる機能というのはフロントエンド側にとりあえずくっついている機能という以上には複雑なものではないかという気もします。(この部分は単独でライブラリとして切り出されたりしないでしょうか)

**Comment by Tatamo** [comment]
> oj コマンドの本来の役割は通常の問題を解くときに使うコマンドである
これで解決していました 失礼しました

**Comment by Tatamo** [comment]
なるほど、ありがとうございます。
個人的な印象として(b.)(d.)がフロントエンド側寄りの部分という認識だったので、(a.)(c.)(e.)はライブラリ側かと思っていました。

>「oj コマンドの本来の役割は通常の問題を解くときに使うコマンドである」

これで解決していました、失礼しました。


問題内容そのものを解析していい感じにやってくれる機能というのはフロントエンド側にとりあえずくっついている機能という以上には複雑なものではないかという気もしますし、この部分も単独でライブラリとして切り出されたりすれば
「通常の問題を解くときに使うライブラリが提供されている」
「APIライブラリ(online-judge-tools)が提供されている」
「`oj`コマンドは上2つを同時に利用できるようにしたwrapper・CLIフロントエンドである」
で自己矛盾はある程度解消されるのではないか、とも思いました。
複数のライブラリをごちゃまぜにしたwrapperとしての煩雑さを`oj`に押し付けて、真の「通常の問題を解くときに使うコマンド」が欲しくなったらそちら側のライブラリだけを使って新しくフロントエンドを作れば良いんじゃないでしょうか

**Comment by kmyk** [comment]
@Tatamo 

「ジャッジサーバと通信するためのライブラリ」はあるが「テストを実行したりするためのライブラリ」がないために、フロントエンドのはずの `oj` コマンドが他ツールのバックエンドとして使われている現状があります。これは認識していて不適切だというのも理解しています。これについては分かります。

他はよく分かりません。
「問題内容そのものを解析していい感じにやってくれる機能」とは具体的に何と何と何と何を指していますか？
online-judge-tools の内部に矛盾はなく、`oj` コマンドを不適切に利用する外部のツールに矛盾 (あるいは取捨選択や設計判断) があるだけなのですが、その状況の責任はどこにあると考えていますか？

**Comment by Tatamo** [comment]
具体的な例はまさしく私の最初のコメントで挙げた通りの分け方での (a.)(c.)(e.) 部分そのもので、フロントエンドとAPIをどこで線引きするかを勘違いしていた以外はそのままの意味です。

問題の取得まではAPI側の責務として、取得した問題を解釈して利用する段階に一つの処理のまとまりがあるのではないかというのが個人的な印象で、これは"問題を解くためのプログラムそのものに""個々の問題に応じた形で"手を加える、という点によって定義されるのではないかと思っています。
この場合、APIの利用のみで取得が完結し、テスト実行自体はプログラムを改変することも問題文のセマンティクスを利用することもなく決められたコマンドを実行するだけでよいので、テスト実行機能などは「内容を解析していい感じにやる」機能には含まれず、単なるAPIのwrapperに過ぎないという印象です。(場合によっては(c.)に関連してテスト時に問題の情報を利用するかもしれないので、あまり厳密ではありませんが)

>「oj コマンドの本来の役割は通常の問題を解くときに使うコマンドである」「現状の online-judge-tools は Python のライブラリも提供している (import onlinejudge などとすると Contest.list_problems() みたいなメソッドがある)」という状況で、これらの責務を曖昧にするサブコマンドは追加したくない気持ちがあるためです。

基本的にはこのような状況は(矛盾と表現したのは正しくなかった気がしますが) `oj` コマンドの立ち位置が定まっていないことによるものかと思いましたので、何か明確に責務と呼べるようなものが `oj` にあるのであれば、ライブラリとして切り出してしまうことで、`oj` コマンドに曖昧なものを押し付けるという方針をとれば一応の解決になるのではないかと思いました。

**Comment by Tatamo** [comment]
> フロントエンドのはずの oj コマンドが他ツールのバックエンドとして使われている

この点については問題意識が受け取れていない気がするのですが、Pythonライブラリから見ると`oj`はフロントエンド側ですが、コマンドとして見ると他のコマンドと組み合わせて使ったり別のプログラムから呼び出したりするのは不自然ではないような気もします。

**Comment by kmyk** [comment]
@Tatamo 

まずそもそもこの issue は「いま (a.),...,(e.) という問題がある。なのでそれを解決したい。そのために新しい wrapper `oj2` を作ろう」というものです。
あなたは「別の問題 (f.) がある。だから `oj` を修正しろ」と言っているように見えます。

このふたつは無関係です。話がずれているようにしか見えません。
その問題 (f.) があることは認識していますので、ここで話を打ち切っていいですか？

**Comment by Tatamo** [comment]
>>少なくともコンテストに紐付いた問題url集合の取得くらいまではojが提供しても良いのではないのでしょうか。
>
>分かります。分かるのだけど、実際にそうすべきかは悩んでいます。
「oj コマンドの本来の役割は通常の問題を解くときに使うコマンドである」「現状の online-judge-tools は Python のライブラリも提供している (import onlinejudge などとすると Contest.list_problems() みたいなメソッドがある)」という状況で、これらの責務を曖昧にするサブコマンドは追加したくない気持ちがあるためです。

これに関連する話をしていると思っていたのですが、オフトピックに寄りすぎてきたようでしたらここで打ち切ってよいかと思います。

~~>少なくともコンテストに紐付いた問題url集合の取得くらいまではojが提供しても良いのではないのでしょうか。~~

~~これはそもそもこのissueに適切でないコメントだったということでしょうか。その後も議論が続いているように見えたのですが。(f.)はこれのことでは？~~

**Comment by Tatamo** [comment]
それで、おそらく本題に戻っていると思いますが、
`oj2`というwrapperコマンドを作る際にatcoder-toolsを基準に再設計するにあたって、問題解析部分もフロントエンドに含むとかなりfatな印象があり、このあたりを予めライブラリとして外部化しておく価値は高いのではないかと考えます。

**Comment by kmyk** [comment]
atcoder-tools がやってるような問題解析部分のライブラリ化はする予定です

**Comment by kmyk** [comment]
https://github.com/kmyk/online-judge-template-generator やっていきしています

**Comment by kmyk** [comment]
ほぼ終了
