### ISSUE TITLE
anything about installation

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#717]
Please write anything about installation. Questions, your workarounds, tips, etc.

**Comment by kmyk** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">online-judge-tools 動かない なぜ</p>&mdash; おきもち (@IKyopro) <a href="https://twitter.com/IKyopro/status/1246694667338395648?ref_src=twsrc%5Etfw">April 5, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">python2なのがやばい？(2.7だった)</p>&mdash; おきもち (@IKyopro) <a href="https://twitter.com/IKyopro/status/1246695339244916736?ref_src=twsrc%5Etfw">April 5, 2020</a></blockquote>

<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">いやpip3が使えないからpipをしたけど不正解なのか、難しすぎる</p>&mdash; おきもち (@IKyopro) <a href="https://twitter.com/IKyopro/status/1246697378792390656?ref_src=twsrc%5Etfw">April 5, 2020</a></blockquote>

**Comment by fukatani** [comment]
あとWindowsユーザーに.exeファイルどうやって使うの？とコドフォで聞かれてしまったので、そこも説明したい。ダウンロードしてパス通すだけなんですけど。

**Comment by kmyk** [comment]
ちなみにとりあえず使うだけならパスを通す必要すらない (フルパスで指定して実行すればよい)

**Comment by kmyk** [comment]
あまり書かれてないから書いておいた方が良さそうなやつ: Windows の人は `oj.exe` を使うこともできる
https://github.com/kmyk/online-judge-tools/releases/latest/download/oj.exe

ただし PATH は通ってないし画面が出ても即終了するかもしれなくて、`cmd.exe` から `C:\Users\[ユーザー名]\Downloads\oj.exe` みたいにパスを直接指定したりする必要はあるかも

**Comment by kmyk** [comment]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">online-judge-toolsをwindows環境に入れようとして無限に嵌っています<br>具体的には、oj dはできるけどoj tでWinError216を吐きます<br>助けてください…</p>&mdash; zacoder (@zacoder1010) <a href="https://twitter.com/zacoder1010/status/1251174972807974914?ref_src=twsrc%5Etfw">April 17, 2020</a></blockquote>

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">大変お恥ずかしい話ですが、VSCodeでtasks.jsonを作成した際に、&quot;command&quot;: &quot;g++&quot;とすべきところを&quot;command&quot;: &quot;c++&quot;としていました。&quot;args&quot;に-o a.exeとしていたため、見かけ上はa.exeが作成されていましたが、もちろんコンパイルはされていませんでした。貴重なお時間を割いていただき恐縮です...</p>&mdash; zacoder (@zacoder1010) <a href="https://twitter.com/zacoder1010/status/1251186371005313026?ref_src=twsrc%5Etfw">April 17, 2020</a></blockquote>

`a.exe` があるけど空ファイルだと `WinError 216` になる

**Comment by kmyk** [comment]
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">VSCodeの拡張ストアからPython再インストールするとｍLinter pylint is not installed.って出て、インストールしようとするとNo such file or directoryと出る</p>&mdash; スギノキ (@ui_mtc) <a href="https://twitter.com/ui_mtc/status/1247590597294051328?ref_src=twsrc%5Etfw">April 7, 2020</a></blockquote>

<blockquote class="twitter-tweet" data-conversation="none"><p lang="ja" dir="ltr">たぶん Windows 上で WSL と VSCode を使ってると思うんですけど、WSL の中 (Ubuntu) と外 (Windows + VSCode) の環境はまったく別なので注意してね。ひとまず VSCode は忘れましょう</p>&mdash; kimiyuki@うさぎ🐇 (@kimiyuki_u) <a href="https://twitter.com/kimiyuki_u/status/1247591586327719936?ref_src=twsrc%5Etfw">April 7, 2020</a></blockquote>

WSL の terminal と VSCode の terminal では環境が別な場合がある (環境が同じな場合もある)

**Comment by kmyk** [comment]
.exe 配布では PATH を通すところまではやってくれないので、.msi を作る必要がありそう

**Comment by kmyk** [comment]
closed. this issue is not so used.
