### ISSUE TITLE
分割 + GitHub Organization

### ISSUE THREAD

**Issue by kmyk** [online-judge-tools/oj#719]
parent: #687

ライブラリ部分とコマンド部分を分離したい。つまり次をしたい:

- ライブラリ `onlinejudge` module を別のレポジトリ (+ Python package) に切り出す
  - [jmerle/competitive-companion](https://github.com/jmerle/competitive-companion) 互換の JSON を吐くコマンドを用意する
- `oj` コマンドはこのレポジトリに残す

---

利点:

- online-judge-tools の上部にツールを作っている開発者にとって楽になる
  - コンテストのパース機能は望まれていた。もともと Python module として提供していたが誰も使ってくれないし、コマンドとして wrap して提供した方がよさそう (https://github.com/kmyk/online-judge-tools/issues/687#issuecomment-590071055 など)
  - ライブラリ利用者に対し自然に [jmerle/competitive-companion](https://github.com/jmerle/competitive-companion) との連携も促せるので、エンドユーザにとっても利益になる
  - 出力が JSON になると API が明確かつ依存が疎になる。
- ライブラリ部分とコマンド部分の責任や役割を自然に分割して明確かつ小さくできる
  - つまり、コードがきれいになり、あまり構造を理解せず拡張してもそう大きくは壊れなくなる
  - ついでに CI の実行も速くかつ失敗が少なくなる

欠点:

- 移行作業をしないといけないので面倒。
- ライブラリ部分とコマンド部分の Python packages が別になる。それぞれのバージョンの組み合わせの問題が発生したり、開発時の連携が取りにくくなったりする。
- issues の移行が面倒。

注意点:

- `oj` コマンドだけの利用者に迷惑をかけないようにしなければならない。レポジトリの分割が行われたことにまったく気付かれないのが理想。これは普通にやれば達成できる。
- @fukatani さんにはライブラリ部分のレポジトリのメンテナをやってほしい。コマンド部分のレポジトリのメンテナを続けるかはどちらでもよい (任せます)。
  - 私は @fukatani に「`oj` コマンドの背景の思想についてあまり理解してくれてない (ユーザとしては十分だが、メンテナとしては不足)」「UX や設計についての判断はまだあまり任せられない」と感じていて、コマンド部分のメンテナは向いてない気がしています。
  - 一方で「[fukatani/rujaion](https://github.com/fukatani/rujaion) を作ってるので、ライブラリ部分に何が必要かはよく理解できているはず」「コードレビューはとても助かっている」「私が失踪したときにメンテを引き継いでくれる人は最低ひとりはほしい」とも思っていて、ライブラリ部分のメンテナはぜひ頼みたい。

cc @kjnh10 @Tatamo

**Comment by kmyk** [comment]
@fukatani これどう思いますか？

**Comment by fukatani** [comment]
各論としては概ね賛成なんですけど、一点だけ言うとRujaionは`oj`をPythonでimportしてて、私としてはPythonの方が便利です。
ただまあ私以外誰も使ってませんし、Emacsやvimプラグイン開発者のためにJSONインターフェースは必要ですし、私のためだけにPython残してとも言いづらい、、言いたい、、

**Comment by fukatani** [comment]
例によって論点がずれるんですけど、私がこうしたらどうでしょうと思っているのは以下の三点です。

・チーム oj (Github organization)を作る
関連プロジェクトのまとまりがわかったり、こんなに多くの人が関わってるプロジェクトなんだと思ってもらうことはライブラリの信用が出てきますし、チームとしての一体感（精神論的な）が出てきたりする気がします。

・チームでojで大改革の全体像とマイルストーンを整理する場を作る
oj-templateと、このJSONの話と、（他にもある？）と色々と壮大な話をされていてすげえ！と思っているんですが、どういう順番で進んでいくかというのと全体的なスケジュール感が気になります。

今のままだとkmykさんががんばるしかなくてでも一人でやると燃え尽きちゃったりしないかなあというのと、
途中のステップがあきらかになれば、「ここは私やります」！ということもできるかもしれないですし。

・kmykさんがリーダーシップを発揮する。メンバーをモチベートする。
正直に言えば時々少しトゲトゲしさを感じます。
忙しいのかしら？持ち前のキャラ？
kmykさんは頭脳は抜群に強くていつも勉強になるんですけど、それにプラスしてチームリーダーとして、こう暖かくも厳しくみたいな、、そんなスタイルが少しづつできてくるとチームもプロジェクトも今のスケールを越えるものになっていくんじゃないでしょうか。

３つのことを言ったんですけど、チーム戦でプロジェクトを進めていったらもっと面白くなるかもしれないですよ？という提案です。でも、一人でやったほうがかえって楽というのもよくある話。

ただそうはいいつつ最近は一時期ほどOSSをやれてないのを自分でも感じます。
会社員と精進するので手一杯です。どうやった黄コーダーになれますか。
あとrujaionもやりたい開発項目が、、

**Comment by kmyk** [comment]
> 各論としては概ね賛成なんですけど、一点だけ言うとRujaionはojをPythonでimportしてて、私としてはPythonの方が便利です。
> ただまあ私以外誰も使ってませんし、Emacsやvimプラグイン開発者のためにJSONインターフェースは必要ですし、私のためだけにPython残してとも言いづらい、、言いたい、、

Python インターフェースは残す予定です。「JSON を吐くコマンド」の形式だと連続で呼び出すときの効率が問題になってくるので内部に踏み込んでの最適化の手段が必要なためです。もし削除することになったとしても、一度 public API として公開したものなので deprecated にしたあと最低半年はメンテを続けたい。

**Comment by kmyk** [comment]
私と似た人とチームで仲良くやるよりも、私とまったく違う考えの人が私が想像もしていなかった良いプログラムを書いてきて「お前のプログラムはこの点がクソだったから改善してより良いものを作った」と見せてくれる方が面白いと感じるので、@fukatani さんの提案する方向に進めたいという気持ちはあまりありません。
いまのところ、骨組となる実装はすべて自分でやり、その肉付け (対応サービスの追加や対応言語の追加など) は他人に任せるのが楽だと思っています。


## GitHub organization の作成について

そろそろあった方がいいのは分かります。特に、関連プロジェクトがまとまっているとユーザにとって分かりやすくてよい。

> チームとしての一体感（精神論的な）が出てきたりする気がします。

「チームとしての一体感」についてはあまりよく分かりません。「一体感」が「一つにまとまったと感じること。グループやその場にいる人々の気持ちや考えが一つにまとまること。」([出展](https://dictionary.goo.ne.jp/word/%E4%B8%80%E4%BD%93%E6%84%9F/)) や「集団が一体化し、一丸となっている感覚。」([出展](https://www.weblio.jp/content/%E4%B8%80%E4%BD%93%E6%84%9F)) だとすれば、政治や同調圧力といった面倒なものを呼び込むリスクの方がこわいので避けたいです。不快な人間と共同で作業をするのが不快で避けたいというのは分かりますが、それ以上は不要で、むしろ「多様性」の方が重要だと思います。

この分割の次のプロダクトが軌道に乗ったぐらいでいいかなと思っていましたが、分割と同時にやってもよい気がしてきました。
(@beet-aizu これをやるとしたら [kmyk/online-judge-verify-helper](https://github.com/kmyk/online-judge-verify-helper) も移すと思うので、何か意見があれば発言してください)


## 議論の場

> チームでojで大改革の全体像とマイルストーンを整理する場を作る

> どういう順番で進んでいくかというのと全体的なスケジュール感が気になります。

順番やスケジュール感は私にも分かりません。気が向いた順番でまんべんなく進めていますし、まだまったく実装したことのない種類のコードが多いので見積りがまったくできません。
ある程度完成したものを見せて「これは成功しそうだな」と思わせないと人間は動かないので、動きだした順に公開することになります。

いま進めているのは次の 3 種です。

- これ
- テストケースの自動生成 https://github.com/kmyk/online-judge-template-generator
- 解法の自動生成 https://github.com/kmyk/Jikka

## @kmyk に関するコミュニケーションの問題

> kmykさんがリーダーシップを発揮する。メンバーをモチベートする。

> 正直に言えば時々少しトゲトゲしさを感じます。

この指摘はかなりありがたい。「暖かくも厳しくみたいな」なのが理想であることとそれが達成できていないことは同意します。
一応は注意してるつもりではあるのですが、「批判するべきものは明確に批判する」「する必要がない発言はせず黙っておく」「政治は避ける」ぐらいの方針で動いているので、お互いにレビューを投げ付けあってたりするとどうしても批判は発生し、さすがにボロがでるのは許してほしい。

ところで、具体的な私の発言 (+ 添削や代替案) も可能なら提示してほしいです。今後の改善に役立てられるためです。

**Comment by kmyk** [comment]
特にコメントないようだし、とりあえず以下で進めようと思います。

1. [kmyk/online-judge-tools](https://github.com/kmyk/online-judge-tools) を fork し kmyk/online-judge-api-client みたいなのを作る。`oj` コマンド部分は [kmyk/online-judge-tools](https://github.com/kmyk/online-judge-tools) に残し、ライブラリ部分は kmyk/online-judge-api-client に移す
2. @fukatani に kmyk/online-judge-api-client のコミット権限を付与。kmyk/online-judge-tools のコミット権限はひとまず削除？
3. online-judge-tools 用の GitHub organization を作り、関連するレポジトリを移動する

**Comment by fukatani** [comment]
腱鞘炎になってきた気がするので、タイピング量抑えようと思ってます。
kmykさんの思う通り進めていただければ。

**Comment by kmyk** [comment]
進めています https://github.com/kmyk/online-judge-api-client

**Comment by kmyk** [comment]
GitHub organization はチームだから私が失踪してもなんとかなるようにできるぽいし、優先度を上げてやります

**Comment by kmyk** [comment]
今までメンテナにコミット権限を積極的に配ってたのはバス係数の増加のためなので、organization 作るなら配らなくていい気がしてきました。ひとまずなしでやります (いいかな？)。

**Comment by kmyk** [comment]
@fukatani この休みで分割と GitHub organization 作成をやります

**Comment by kmyk** [comment]
- [x] GitHub organization を作る
- [x] @fukatani さんのコミット権限を無効に
- [x] コミット権限がある人は被レビューなしでプルリクをマージできるように
- [ ] library 側から command 部分を削除
- [ ] command 側から library 部分を削除
- [ ] すべての repository を organization に移す

**Comment by kmyk** [comment]
連絡: @fukatani @beet-aizu 操作ミスでなにかの invitation が飛んでいきましたが無視してください

**Comment by kmyk** [comment]
残りは API documents のみなので
