### ISSUE TITLE
oj command fails with `ModuleNotFoundError: No module named 'onlinejudge.__about__'` in version 10.0.0

### ISSUE THREAD

**Issue by szk18** [online-judge-tools/oj#755]
はじめまして、
今朝、online-judge-toolsをインストールしてojコマンドを使用しようとしましたが、うまくいかなかったので報告します。
インストール手順に従ってインストールを行い、README.mdのFAQも読みました。
私の環境が悪かったり、online-judge-toolsの不具合でなければcloseしてください。
よろしくお願いします。

私の環境は以下のとおりです
macOS Mojave 10.14.6
$ python3 --version
Python 3.8.0
$ pip3 --version
pip 20.1

実行したコマンドは以下のとおりです。
$ pip3 uninstall online-judge-tools #一度アンインストール
Successfully uninstalled online-judge-tools-10.0.0
$ pip3 install --user online-judge-tools
(略)
Successfully installed online-judge-tools-10.0.0
$ oj 
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 5, in <module>
    from onlinejudge_command.main import main
  File "/usr/local/lib/python3.7/site-packages/onlinejudge_command/main.py", line 11, in <module>
    import onlinejudge_command.update_checking as update_checking
  File "/usr/local/lib/python3.7/site-packages/onlinejudge_command/update_checking.py", line 11, in <module>
    import onlinejudge.__about__ as api_version
ModuleNotFoundError: No module named 'onlinejudge.__about__'

**Comment by fukatani** [comment]
`python3`コマンドでPython3.8が呼ばれているけど、`pip3`はPython3.7を使ってそうなのは問題ないかな、多分。

https://github.com/online-judge-tools/oj/blob/55c801a34d7f7f277b1379c5b77b28626fc9e37e/onlinejudge_command/update_checking.py#L11

@kmyk 
ここが`import onlinejudge.__about__ as api_version`で`onlinejudge_command`になってないのっていいんでしたっけ？

**Comment by fukatani** [comment]
@szk18 
お手数ですが、
```
pip3 uninstall online-judge-tools
pip3 install --user --no-cache-dir online-judge-tools
```
を試していただけないでしょうか？
またログを省略せずに貼っていただけると助かります。

**Comment by szk18** [comment]
@fukutani 

上記のコマンドの結果を添付します。

$ pip3 uninstall online-judge-tools
Found existing installation: online-judge-tools 10.0.0
Uninstalling online-judge-tools-10.0.0:
  Would remove:
    /Users/suzukikensuke/.local/bin/oj
    /Users/suzukikensuke/.local/lib/python3.8/site-packages/online_judge_tools-10.0.0.dist-info/*
    /Users/suzukikensuke/.local/lib/python3.8/site-packages/onlinejudge_command/*
    /Users/suzukikensuke/.local/lib/python3.8/site-packages/tests/_implementation/*
Proceed (y/n)? y
  Successfully uninstalled online-judge-tools-10.0.0
$ pip3 install --user --no-cache-dir online-judge-tools
Collecting online-judge-tools
  Downloading online_judge_tools-10.0.0-py3-none-any.whl (36 kB)
Requirement already satisfied: diff-match-patch>=20181111 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-tools) (20181111)
Requirement already satisfied: requests>=2 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-tools) (2.22.0)
Requirement already satisfied: colorama>=0.3 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-tools) (0.4.3)
Requirement already satisfied: online-judge-api-client<11,>=10 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-tools) (10.0.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (2019.11.28)
Requirement already satisfied: lxml>=4 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (4.5.0)
Requirement already satisfied: jsonschema>=3.2 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (3.2.0)
Requirement already satisfied: appdirs>=1 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (1.4.3)
Requirement already satisfied: beautifulsoup4>=4 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (4.9.0)
Requirement already satisfied: toml>=0.10 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (0.10.0)
Requirement already satisfied: attrs>=17.4.0 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (19.3.0)
Requirement already satisfied: six>=1.11.0 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (1.14.0)
Requirement already satisfied: setuptools in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (41.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (0.16.0)
Requirement already satisfied: soupsieve>1.2 in ./.pyenv/versions/3.8.0/lib/python3.8/site-packages (from beautifulsoup4>=4->online-judge-api-client<11,>=10->online-judge-tools) (2.0)
Could not build wheels for diff-match-patch, since package 'wheel' is not installed.
Could not build wheels for requests, since package 'wheel' is not installed.
Could not build wheels for colorama, since package 'wheel' is not installed.
Could not build wheels for online-judge-api-client, since package 'wheel' is not installed.
Could not build wheels for urllib3, since package 'wheel' is not installed.
Could not build wheels for idna, since package 'wheel' is not installed.
Could not build wheels for chardet, since package 'wheel' is not installed.
Could not build wheels for certifi, since package 'wheel' is not installed.
Could not build wheels for lxml, since package 'wheel' is not installed.
Could not build wheels for jsonschema, since package 'wheel' is not installed.
Could not build wheels for appdirs, since package 'wheel' is not installed.
Could not build wheels for beautifulsoup4, since package 'wheel' is not installed.
Could not build wheels for toml, since package 'wheel' is not installed.
Could not build wheels for attrs, since package 'wheel' is not installed.
Could not build wheels for six, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.
Could not build wheels for pyrsistent, since package 'wheel' is not installed.
Could not build wheels for soupsieve, since package 'wheel' is not installed.
Installing collected packages: online-judge-tools
  WARNING: The script oj is installed in '/Users/suzukikensuke/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed online-judge-tools-10.0.0

$ oj 
Traceback (most recent call last):
  File "/usr/local/bin/oj", line 5, in <module>
    from onlinejudge_command.main import main
  File "/usr/local/lib/python3.7/site-packages/onlinejudge_command/main.py", line 11, in <module>
    import onlinejudge_command.update_checking as update_checking
  File "/usr/local/lib/python3.7/site-packages/onlinejudge_command/update_checking.py", line 11, in <module>
    import onlinejudge.__about__ as api_version
ModuleNotFoundError: No module named 'onlinejudge.__about__'

**Comment by masutech16** [comment]
szk18さんと同じ症状が出ています。
ログを見てwheelがinstallされていないことが原因かなと思いこちらでも提示されていたコマンドを試しましたが、wheelの部分を解消しても同様のエラーが出ることを確認しました。

```
$ pip3 install --user --no-cache-dir online-judge-tools
Collecting online-judge-tools
  Downloading online_judge_tools-10.0.0-py3-none-any.whl (36 kB)
Requirement already satisfied: requests>=2 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-tools) (2.23.0)     
Requirement already satisfied: diff-match-patch>=20181111 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-tools) (20181111)
Requirement already satisfied: colorama>=0.3 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-tools) (0.4.3)    
Requirement already satisfied: online-judge-api-client<11,>=10 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-tools) (10.0.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from requests>=2->online-judge-tools) (3.0.4)
Requirement already satisfied: toml>=0.10 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (0.10.0)
Requirement already satisfied: beautifulsoup4>=4 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (4.8.2)
Requirement already satisfied: jsonschema>=3.2 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (3.2.0)
Requirement already satisfied: appdirs>=1 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (1.4.3)
Requirement already satisfied: lxml>=4 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from online-judge-api-client<11,>=10->online-judge-tools) (4.5.0)
Requirement already satisfied: soupsieve>=1.2 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from beautifulsoup4>=4->online-judge-api-client<11,>=10->online-judge-tools) (2.0)
Requirement already satisfied: setuptools in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (41.2.0)
Requirement already satisfied: six>=1.11.0 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (1.14.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (0.16.0)
Requirement already satisfied: attrs>=17.4.0 in /home/masutech/.anyenv/envs/pyenv/versions/3.8.1/lib/python3.8/site-packages (from jsonschema>=3.2->online-judge-api-client<11,>=10->online-judge-tools) (19.3.0)
Installing collected packages: online-judge-tools
Successfully installed online-judge-tools-10.0.0

$ oj
Traceback (most recent call last):
  File "/home/masutech/.local/bin/oj", line 5, in <module>
    from onlinejudge_command.main import main
  File "/home/masutech/.local/lib/python3.8/site-packages/onlinejudge_command/main.py", line 11, in <module>
    import onlinejudge_command.update_checking as update_checking
  File "/home/masutech/.local/lib/python3.8/site-packages/onlinejudge_command/update_checking.py", line 11, in <module>
    import onlinejudge.__about__ as api_version
ModuleNotFoundError: No module named 'onlinejudge.__about__'
```

環境はWindows 10 WSL(Ubuntu Legacy)にpyenvでpython3.8.1を入れて使っています。

**Comment by masutech16** [comment]
連投失礼します。こちらの方では`online-judge-api-client`を入れなおすことで正常に動作するようになりました。具体的には以下のコマンドを実行しました。
```shell
$ pip3 uninstall online-judge-api-client
$ pip3 install online-judge-api-client
```

**Comment by fukatani** [comment]
みなさん、ご報告ありがとうございます。ご迷惑をおかけしております。

見る限り、ojがapi-clientと別れた変更が入ったのが関係ありそうですが、`online-judge-api-client`のインストールには成功してそうで、原因調査中です。

すぐに使いたい方は前バージョンの9.2.2を試していただけないでしょうか？
```
pip3 uninstall online-judge-tools
pip3 install online-judge-tools==9.2.2
```

また、これでも動かないという方がいたら報告をお願いします。

**Comment by szk18** [comment]
pythonのdockerコンテナ内で `$ pip3 install online-judge-tools` をすると正常にインストールが成功し、ojコマンドも叩けました。
もう少し確認してみますが、こちらの環境が悪い可能性がありそうです。

**Comment by fukatani** [comment]
ご報告ありがとうございます。
とりあえず、二人共動作したということで安心しましたが、このイシューは開いたままでお願いします。

**Comment by szk18** [comment]
連投失礼します。
ローカル環境でpyenvをアンインストールした後、
Python 3.7.6 pip 19.3.1 で正常にインストールが成功し、ojコマンドが叩けることを確認しました。

**Comment by fukatani** [comment]
まだpyenvが原因と決まったわけではないですが、以下一般論です。
一般にpyenvはトラブルが起きがちで、生のPython/pipを使うのが一番トラブルがなくてスムーズだと思うので初学者ということであればそこからはじめてみるのでいいと思います。

Pythonをやっているうちに使いたいライブラリが増えてきて、AというライブラリはCのバージョン1が必要だが、Bというライブラリはバージョン2が必要である、
みたいなややこしいことが置き始めたら、virtualenvのようなものを使いたくなります。

ただしこの段階でもまだpyenvは不要です。
ライブラリ開発者には例えばojの動作をPython3.8とPython3.7でローカルで動作させて両方で正常に動くかテストしたいというニーズはあり、こういう時はpyenvを使うメリットがあります。

**Comment by fukatani** [comment]
@kmyk 
pipコマンドを叩いて、`Successfully installed online-judge-tools-10.0.0`と表示している以上、そこがdockerであれpyenvであれWSLであれ、正常に動作する必要があります。
現状ojは使用時にアップデートをすすめるのにもかかわらず、アップデートしたら動かなくなった、ということがコンテスト中または直前に起きた場合、ユーザーにリスクを与えるかもしれません。
現に二人使えなくなった方がいるので、対応できるまで、10.0.0を一旦撤回してもいいのではないでしょうか。

**Comment by kmyk** [comment]
とりあえず 10.0.0 を無効化しました。これ以上影響が広がることはありません。
pyenv についてはよく分からないので後で調べます。

**Comment by kmyk** [comment]
情報募集: pyenv を使ってないのに壊れてしまった人はいますか？

**Comment by kmyk** [comment]
原因を理解しました。`onlinejudge` module の所属する package を移したこと、pip の install / uninstall の処理順序が原因で壊れています。

(1.) online-judge-api-client=10.0.2 を install, (2.) online-judge-tools==9.2.2 を uninstall, (3.) online-judge-tools==10.0.0 を install という順序で処理が進むので、(1.) で作成された `onlinejudge` module が (2.) で削除されてしまっています。

**Comment by kmyk** [comment]
根本解決は不可能だったので module 名を変更する形でむりやり解決しました。具体的には、`onlinejudge` module だけでなく、同一の内容の `onlinejudge_workaroud_for_conflict` module を追加で用意し、こちらを用いるようにしました。oj コマンドを利用する限りにおいては影響はなくなったはずです。

---

`onlinejudge` module に依存している他のツールについては影響が残ります。
これは以下のいずれかによって解決できます:

- `onlinejudge.service` module などを import してみて失敗したらエラーメッセージを出す (例: https://github.com/online-judge-tools/api-client/pull/30/commits/7221b571dac6f540eb31af1f7e2f8eb0359b2131)
- https://github.com/online-judge-tools/api-client の JSON interface に乗り換える
- (非推奨) `onlinejudge_workaroud_for_conflict` module を使う

実質的な互換性破壊で申し訳ないですが、影響ある人はよろしくお願いします。
cc @fukatani @kjnh10 @beet-aizu
