### ISSUE TITLE
Add PyPy as primary suggestion for .py file while submitting.

### ISSUE THREAD

**Issue by blue-edge-techno** [online-judge-tools/oj#760]
Add a choice action b/w python and PyPy or a one-time selection which can be manually changed later.
Because PyPy proves to be much faster and helpful during cp than Python.

Also, add a password masking functionality while login with the console.

**Comment by kmyk** [comment]
`oj s --guess-python-interpreter pypy main.py` will work. Please use this.
If you feel this is too long, you can add alias like `alias oj-s-pypy='oj s --guess-python-interpreter pypy'` for your shell.

Or, if many users demands, I'll add for a shortcut option (e.g. `--pypy`) or a guessing feature from the shebang (i.e. strings something like `#!/usr/bin/env pypy3`). 

(for the problem of a password masking, go #761)
