### ISSUE TITLE
oj login https://codeforces.comでエラーを吐いてしまう

### ISSUE THREAD

**Issue by yosupo06** [online-judge-tools/oj#771]
maroonがonline-judge-toolsを使っていたら、突然下記の画像のようなエラーを吐いて死ぬとのことです。
本人はgithubが生理的に無理らしいので代理で書き込みます。意味がわからないと思うので、意味がわからなかったらcloseしてください…

![image](https://user-images.githubusercontent.com/7629145/81293172-d4a8ec80-90a7-11ea-9cdb-790257b8897e.png)

**Comment by beet-aizu** [comment]
せめてversionの情報くらいないとなにもわからなさそう

**Comment by kmyk** [comment]
#775 あたりの問題に巻き込まれている可能性があって、以下を試してみてもらってほしいです

``` console
$ pip3 install --force-reinstall --upgrade online-judge-tools
$ pip3 install --force-reinstall --upgrade online-judge-api-client
```

**Comment by beet-aizu** [comment]
issue番号が未来を指していそうです

**Comment by maroon66** [comment]
kmyk さんのを試しましたが変わりません
![image](https://user-images.githubusercontent.com/21185997/81296031-3f5c2700-90ac-11ea-89a0-b621b7992307.png)

**Comment by kmyk** [comment]
最新の online-judge-tools と online-judge-api-client と古い online-judge-tools の 3 つが同時にインストールされていてこれらが干渉し、古い online-judge-tools と online-judge-api-client のキメラが動いているように見えます。

以下を実行するとインストールされている `oj` を全部消去できると思うので、これをやってからもう一度インストールしてみてほしいです。

``` console
$ pip3 uninstall online-judge-tools online-judge-api-client
$ pip3 uninstall online-judge-tools online-judge-api-client
$ sudo pip3 uninstall online-judge-tools online-judge-api-client
$ sudo pip3 uninstall online-judge-tools online-judge-api-client
$ rm "$(which oj)"
$ rm "$(which oj)"
$ rm -rf "$(python3 -c 'import pathlib, onlinejudge ; print(pathlib.Path(onlinejudge.__file__).parent)')"
$ rm -rf "$(python3 -c 'import pathlib, onlinejudge ; print(pathlib.Path(onlinejudge.__file__).parent)')"
```

**Comment by maroon66** [comment]
うまく行きました，ありがとうございます
