### ISSUE TITLE
It should be better to revise the name of section "stress test" to "random testing" [document enhancement] 

### ISSUE THREAD

**Issue by zfhrp6** [online-judge-tools/oj#799]
this suggest a document enhancement.

the section name of "Stress test" (「ストレステスト(ja)」) could mislead, because the testing in the section do not determine the stability of codes you will submit nor judging systems.
I suggest to change the section name to any of the below

* Random tesing (ランダムテスト(ja))  (if the testing means to choose some inputs/outputs pairs randomly)
* Exhaustive testing (全数テスト(ja)) (if to test all i/o pairs)

**Comment by kmyk** [comment]
Yes, the name "Stress test" is not so appropriate. I agree replacing the name.
This current name is based on only a historical reason. At a certain point in the past, in the competitive programming community in Japan, the sole word 「ストレステスト」 was used to describe such a test. So I've borrowed the name.

BTW, there are more options:

- [Fuzzing](https://en.wikipedia.org/wiki/Fuzzing) or Fuzz testing (if you want to emphasis that the inputs which causes crash are unknown)
- Property-based testing (e.g. [QuickCheck](https://en.wikipedia.org/wiki/Fuzzing) in Haskell) (if you consider that "matching with the naive solution" is one of expected properties)

I think "Fuzzing" is the best choice. What do you think?

**Comment by zfhrp6** [comment]
Okey. I didn't know that reason, so we might need an annotation about the historical idiom ("Stress test").

great options. I think **Fuzzing** suits, too.

**Comment by kmyk** [comment]
Once I'm going to use "Fuzzing", but I finally used "Random testing", as you suggested at first.
"Fuzzing" is highly associated with the security, so this might introduce another criticism.

> My analysis of words related to our "testing":
>
> -   The name "Stress testing" implies using the larger load than normal situation.
>     -   Sometimes, you are doing our "testing" to increase the plausibility about the fact that your code has no bug. For example, in Codeforces, even when your code passes the pretest and you believe there are no bugs, you can do the "testing" for more safety. In Topcoder Marathon Match, some people do this in very large scale using cloud environments. In this situation, I feel that the name "Stress testing" is appropriate.
> -   The name "Random testing" is the most plain name.
>     -   At least, to avoid criticism around the name, this is the best choice.
>     -   This name is very simple, so strong in terms of meme. We can easily replace with this.
> -   The name "Fuzzing" (or "Fuzz testing") seems also a good choice, but this name is strongly associated with the security.
> -   The name "Property-based testing" (e.g. QuickCheck) is a similar concept, but the "property" should mean more concrete and definite one (e.g. idempotence, associativity, etc.).
> -   The name "Exhaustive testing" is related, but in most cases, the space of inputs is too large to exhaust.
>     -   However, if possible, we should always do the exhaustive testing. Actually it's sometimes possible. This implies that the randomness is not an essential property of our "testing".
>
> (commit message of https://github.com/online-judge-tools/oj/pull/844/commits/a1439c91e207e18c6515758ab9d111a4f6f38144)
