### ISSUE TITLE
StreamHandlerを標準エラー出力から標準出力に変更する

### ISSUE THREAD

**Issue by ryo-n** [online-judge-tools/oj#824]
## Description

StreamHandlerを標準エラー出力から標準出力に変更する

## Possible implementations and the analysis (optional)

main.py内でのハンドラ設定部分で下記のようにstdoutを設定することで可能

```
handler = StreamHandler(sys.stdout)
```

## Other notes

-   Will you try to create a pull request?
    -   yes

**Comment by kmyk** [comment]
closed by #825
