### ISSUE TITLE
Skip RE on output generator when `oj generate-input --hack`

### ISSUE THREAD

**Issue by jellc** [online-judge-tools/oj#863]
## Description / 説明

`oj generate-input` コマンドの hack 機能に関して細かな希望(?)です。
`--hack-expected` で指定した出力生成用のプログラムにおいて Runtime error が発生した場合、現状だとそのテストケースはスキップされます。オプションの指定などにより、そのような入力を発見したタイミングで break してその内容を報告させることができると嬉しいです。

## Motivation / 動機

以下が可能になるはずです。

- Output generator 側の明らかなバグの発見
- `--hack-expected` と `--hack` に同一ファイルを指定することによる assert debug

## Other notes / その他

-   Will you try to create a pull request?
    - まだこのパッケージの設計がよく理解できてないので難しそうです。。

**Comment by kmyk** [comment]
いい案だなあと思ったまま面倒で放置してしまってたけどついに実装しました
