### ISSUE TITLE
Add `test-interactive` as an alias of `test-reactive`

### ISSUE THREAD

**Issue by cai-lw** [online-judge-tools/oj#886]
## Description / 説明
Add `test-interactive` as an alias of `test-reactive`

## Motivation / 動機
"Interactive" is the more commonly accepted name for problems that require talking to another program. I have not seen people calling them "reactive" either in English or in Japanese.

## Other notes / その他
I personally prefer to gradually deprecate `test-reactive` as well, but that's not necessary.

-   Will you try to create a pull request?
    -   yes

**Comment by kmyk** [comment]
LGTM to add aliases and gradually deprecate `test-reactive`.
You can do this with editing [onlinejudge_command/main.py](https://github.com/online-judge-tools/oj/blob/master/onlinejudge_command/main.py).

I remember that both "reactive" and "interactive" were used when I wrote the early version of `oj` command (5 years ago, in Japanese), but now "interactive" is obviously common, and "reactive" is not used.
