### ISSUE TITLE
`--display-mode=diff-all` ですべての行が表示されない

### ISSUE THREAD

**Issue by hasegawa1** [online-judge-tools/oj#902]
## Summary / 概要

`--display-mode=diff-all` ですべての行が表示されません。私の経験上、最終行のみが表示されません。最終行以外は合っていて最終行のみ間違えているときは WA がでるので表示のみの問題だと推測します。

## Steps to reproduce / 再現方法

1.  `oj t -M diff-all`

environments:

-   version: online-judge-tools 11.5.0 (+ online-judge-api-client 10.10.0)

## Expected behavior / 期待される挙動

`oj t -M diff` の出力です。
![image](https://user-images.githubusercontent.com/36944206/132996695-369a16d0-5503-4d1d-9db8-3d232ad85d03.png)

## Actual behavior / 実際の挙動

![image](https://user-images.githubusercontent.com/36944206/132996712-03571ac3-5a89-48e2-ab8e-62498b2fbcd4.png)

## Other notes / その他

- `--display-mode=all` の出力は正しそうです。
-   Will you try to create a pull request?
    -   no

**Comment by kmyk** [comment]
報告ありがとうございます (やばいバグだ…)。修正したので v11.5.1 に update して使ってください

**Comment by hasegawa1** [comment]
こちらこそ、素早い修正ありがとうございます。
